# Generated by Django 5.1.1 on 2024-09-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_created_user_created_at_listing_listingphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photos',
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='listing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listing'),
        ),
    ]
