# Generated by Django 5.1.1 on 2024-09-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronics'), ('SU', 'Supplies'), ('SE', 'Services')], default='EL', max_length=2),
        ),
    ]
