# Generated by Django 5.1.1 on 2024-09-30 14:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_listing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_unit', models.CharField(choices=[('OT', 'OneTime'), ('HR', 'Hourly'), ('DY', 'Daily'), ('WK', 'Weekly')], max_length=2)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.listing')),
            ],
            options={
                'unique_together': {('listing', 'time_unit')},
            },
        ),
    ]
