# Generated by Django 5.1.1 on 2024-10-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_offer_scheduled_end_offer_scheduled_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
