# Generated by Django 5.1.1 on 2024-10-26 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0.5, message='Rating must be at least 0.5'), django.core.validators.MaxValueValidator(5, message='Rating cannot exceed 5')]),
        ),
    ]
