# Generated by Django 5.1.1 on 2024-09-11 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='created_at',
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('EL', 'Electronics'), ('FU', 'Furniture'), ('CL', 'Clothing'), ('BO', 'Books'), ('OT', 'Other')], default='EL', max_length=2)),
                ('listing_type', models.CharField(choices=[('RE', 'Rental'), ('SE', 'Service')], default='RE', max_length=2)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_photos/')),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_photos', to='core.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='photos',
            field=models.ManyToManyField(blank=True, to='core.listingphoto'),
        ),
    ]
