# Generated by Django 5.1.1 on 2024-09-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_listing_photos_alter_listingphoto_listing_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingphoto',
            old_name='listing_id',
            new_name='listing',
        ),
    ]
