# Generated by Django 5.1.1 on 2024-10-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_listingrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingrate',
            name='time_unit',
            field=models.CharField(choices=[('OT', 'OneTime'), ('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
    ]
