# Generated by Django 5.1.1 on 2024-10-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('D', 'Paid'), ('C', 'Declined')], default='P', max_length=1),
        ),
    ]
