# Generated by Django 5.1.1 on 2024-10-12 06:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_transaction_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='scheduled_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='scheduled_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='time_delta',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='time_unit',
            field=models.CharField(choices=[('OT', 'OneTime'), ('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly')], default='H', max_length=2),
        ),
    ]
